# Copyright Contributors to the L3AF Project.
# SPDX-License-Identifier: Apache-2.0
#
# For documentation on the github environment, see
# https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
#
# For documentation on the syntax of this file, see
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions

name: CI Ubuntu build
on:
  pull_request: {}
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Setup Go 1.21.3
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 
        with:
          go-version: '1.21.3'

      - name: Harden Runner
        uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install gcc libc-dev bash perl curl make

      - name: Checkout repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 

      - name: Format
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          res="$(goimports -l .)"
          if [[ "$(printf '%s' "$res")" != '' ]]; then
            echo "Unformatted source code:"
            echo "$res"
            exit 1
          fi

      - name: Vet
        run: |
          go vet ./...

      - name: Test
        run: |
          sudo go test ./...
          go clean -modcache

      - uses: dominikh/staticcheck-action@ba605356b4b29a60e87ab9404b712f3461e566dc 
        with:
          version: "2023.1.1"
          install-go: false
          cache-key: "1.21.x"

      - name: Build
        run: |
          make

      - uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3
        with:
          name: l3afd-latest-linux-x86_64
          path: l3afd
